### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by robertw** [borski/ha-lucidmotors#1]
PI 4 

Core
2023.11.2
Supervisor
2023.11.3
Operating System
11.1
Frontend
20231030.2

Could not configer in Intergrations tried rebooting installing uninstall and install again no go

Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

Unable to install package lucidmotors @ git+https://github.com/nshp/python-lucidmotors: ERROR: Cannot install lucidmotors==0.1.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by borski** [comment]
@robertw Please try the latest from main; it should be fixed now. Can you confirm?

**Comment by robertw** [comment]
This error originated from a custom integration.

Logger: custom_components.lucidmotors.config_flow
Source: custom_components/lucidmotors/config_flow.py:61
Integration: Lucid Motors
First occurred: 2:51:00 AM (2 occurrences)
Last logged: 2:51:24 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/lucidmotors/config_flow.py", line 61, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lucidmotors/config_flow.py", line 36, in validate_input
    await api.login(data["username"], data["password"])
  File "/usr/local/lib/python3.11/site-packages/lucidmotors/__init__.py", line 176, in login
    reply = LoginResponse(**raw_reply)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for LoginResponse
userVehicleData -> 0 -> vehicleState -> softwareUpdate -> updateState
  value is not a valid enumeration member; permitted: 'UPDATE_FAILED_DRIVE_ALLOWED', 'UPDATE_SUCCESS_WITH_WARNINGS', 'UNKNOWN_UPDATE_STATE', 'IN_PROGRESS' (type=type_error.enum; enum_values=[<UpdateState.UPDATE_FAILED_DRIVE_ALLOWED: 'UPDATE_FAILED_DRIVE_ALLOWED'>, <UpdateState.UPDATE_SUCCESS_WITH_WARNINGS: 'UPDATE_SUCCESS_WITH_WARNINGS'>, <UpdateState.UNKNOWN: 'UNKNOWN_UPDATE_STATE'>, <UpdateState.IN_PROGRESS: 'IN_PROGRESS'>])

**Comment by borski** [comment]
Oh, I see! Can you do me a favor and grab python-lucidmotors, and then generate an anonymized test case from your data, using examples/anonymize_login_response.py. This will log in, remove identifying information from the API response, and write it to a file. Check the file to ensure anonymization actually worked, then you can share it as a test case.

Feel free to post it here or email it to borski@owlpost.lol

**Comment by robertw** [comment]
Sent via email

**Comment by borski** [comment]
> Sent via email

Haven't received it yet - mind resending? You can also use michael.borohovski@gmail.com

**Comment by robertw** [comment]
I just forwarded it I guess there was an email error it did not create a
file but I did a screen grab

**Comment by borski** [comment]
You had a permission error when trying to save the file (needs to have write access to the local directory), but I think @nshp fixed your issue last night. Give me a few minutes to cut a release.

**Comment by borski** [comment]
@robertw Try updating the HA component to v0.1.1, and please let me know if that fixes your issue.

**Comment by robertw** [comment]
It's looking good loaded fine took the passwords fine.... Great job guys

**Comment by borski** [comment]
Glad it's working! :)
