### ISSUE TITLE
Reformat reported value of sensor 'charge_session_time_remaining"

### ISSUE THREAD

**Issue by jgoldman1** [borski/ha-lucidmotors#11]
Sensor "sensor.{vehiclename}_charge_session_time_remaining" reports back an oddly formatted value... not something very human readable like other sensors.  Mine reports '1092:15:00', however this is when there's no charge session running, so not sure if the formatting is odd only for the case of no charging in process, or always.   Haven't checked it during a charge session

**Comment by nshp** [comment]
I think that's a max value used when there is no charge session - we should just catch that and set it to Unavailable or something. The formatting is HA's problem though - it just doesn't display durations longer than hours well. We could format it ourselves, but that would just make automations more difficult.

**Comment by acronce** [comment]
It looks like that sensor returns 65535 when charging is not happening. @jgoldman1 you can work around this by wrapping the sensor in an availability template (substitute your vehicle name):


```
# Lucid Air sensor templates
- platform: template
  sensors:
    lucid_air_charge_session_time_remaining_template:
      friendly_name: "Lucid Air Charge session time remaining template"
      device_class: duration
      unit_of_measurement: minutes
      availability_template: >-
        {% if states('sensor.lucid_air_charge_session_time_remaining') | int == 65535 %}
          unavailable
        {% else %}
          true
        {% endif %}
      value_template: >-
        {{ states('sensor.lucid_air_charge_session_time_remaining') }}
```

Then just use the template as the entity in your dashboard card instead of the original one.

If you don't want the sensor to appear unavailable when not charging, you could instead just change the `value_template` to return 0 when it sees 65535.

```
- platform: template
  sensors:
    lucid_air_charge_session_time_remaining_template:
      friendly_name: "Lucid Air Charge session time remaining template"
      device_class: duration
      unit_of_measurement: minutes
      value_template: >-
        {% if states('sensor.lucid_air_charge_session_time_remaining') | int == 65535 %}
          0
        {% else %}
          {{ states('sensor.lucid_air_charge_session_time_remaining') }}
        {% endif %}
```
