### ISSUE TITLE
Not working with non US account

### ISSUE THREAD

**Issue by wissamoh** [borski/ha-lucidmotors#16]
Hello this integration is not working for non-US accounts...is there a way to make it work?

Thanks.

**Comment by nshp** [comment]
You're absolutely right, you're the first non-US owner we've heard from.

I think I added support for other regions to the underlying library correctly, could you try https://testmycode.cc to make sure that actually works? If so adding support to HA should be easy.

**Comment by wissamoh** [comment]
Hi @nshp 
Thanks for your fast response. You’re awsome.
Actually I tried to log in using https://testmycode.cc however the terst reterned the following error :

“ Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.”

Note: my region is “saudi arabia”

any clues?

Thanks

**Comment by nshp** [comment]
Oops, had a bug in there when there are no charging accounts listed in your account. Give it another shot?

**Comment by wissamoh** [comment]
@nshp 
It worked now and i could fetch all the car information.
Now how can we reflect this to the HA integration 😊?

thanks.

**Comment by nshp** [comment]
Great, thanks for checking! In that case we basically just need to add a region selection field to the integration setup wizard. I should be able to do this tonight. Please do submit your data via testmycode as well (button at the top of the page) - I would not be surprised if there are some unknown bits of information in there that differ between regions.

**Comment by nshp** [comment]
Added a region selector to the setup wizard in 66f3860136f4152b3de8b5bb58e581eaa355a3f0. I'll work on some of the other open issues and get a new release out over the next few days.

**Comment by wissamoh** [comment]
Hello @nshp 
Thanks for your update.
I have submitted the data as you requested too.

**Comment by wissamoh** [comment]
Hello @nshp 
May I know when are you going to release the new updated version?
Thanks.

**Comment by wissamoh** [comment]
Hello @nshp 
I have tried to initialize the lucid setup after copying the source code manually. but unfortunately the initialization failed. I have checked the logs and found the following log error 
<img width="1001" alt="Screenshot 2024-05-15 at 7 52 23 PM" src="https://github.com/borski/ha-lucidmotors/assets/33606709/99f7d7d9-a3eb-42c2-b9d3-c37f2076d132">

**Comment by nshp** [comment]
Whoops, thanks for the bump, I'll push a release out today.

**Comment by nshp** [comment]
New release is up, look for v1.0.5.
Make sure you delete old versions of the integration if you installed it manually and let us know how this new one goes.

**Comment by wissamoh** [comment]
> New release is up, look for v1.0.5. Make sure you delete old versions of the integration if you installed it manually and let us know how this new one goes.

Hello @nshp , 
I removed the old integration and did a fresh install. Unfortunately the intergation failed after the initialization. and please find attached below the error from the logs.

<img width="1013" alt="Screenshot 2024-05-16 at 9 07 10 AM" src="https://github.com/borski/ha-lucidmotors/assets/33606709/7c69a9df-b566-472c-82c3-7b7028618062">

**Comment by nshp** [comment]
Bah, found my mistake, I only passed through the region for the initial validation. Fix incoming as 1.0.6.

**Comment by wissamoh** [comment]
Hello @nshp 
Thanks for the update. It worked perfectly now.
However, I have a couple of questions:
1- why the climate control is not showing in the control section…while I have all the other controls showing
2- how can I get the graphical version of lovelace to work? I can only see normal entities and controls…

**Comment by nshp** [comment]
> 1- why the climate control is not showing in the control section…while I have all the other controls showing
Doesn't it?
This is what mine looks like on the "device info" page
<img width="678" alt="Screenshot 2024-05-18 at 5 05 14 PM" src="https://github.com/borski/ha-lucidmotors/assets/5840704/4a05411a-cb27-429f-8c5d-7ade3b5ddd31">
5th item down in the controls is climate control, which you can click for actual controls.
We don't really have much control over those auto-generated widgets either way.

2- how can I get the graphical version of lovelace to work? I can only see normal entities and controls…
Not sure what graphical version you mean?

**Comment by wissamoh** [comment]
Hello @borski , Long time on this thread. I'm now facing the device initialization issue again. After some investigation I found that Lucid has made some changes to the regions. Now they have 4 regions:
United States --> which maps to Region.us

Saudi Arabia --> which is depreciated ...and no longer working with Saudi account login even in Lucid app...this one is now replaced by the middle east region

Europe --> which maps to Region.EU

and a new region is introduced 

Middle East --> which Maps to Region.ME


I have made the required changes on the config_flow.py file as per the picture and all is working fine... I would appreciate if you can please reflect this on you upcoming update. 

Note: I have changed the region for Saudi Arabia to Region.eu as well so it doesn't break my current device...it was the only way 

<img width="914" alt="Image" src="https://github.com/user-attachments/assets/148dd27c-6bdb-4509-a753-c2d760bc2a25" />

**Comment by borski** [comment]
Thanks @wissamoh! We don’t have many Saudi users yet (or maybe we do, but I don’t know them! :p) so this is super helpful.

**Comment by wissamoh** [comment]
> Thanks @wissamoh! We don’t have many Saudi users yet (or maybe we do, but I don’t know them! :p) so this is super helpful. 

Well you do for sure I'm using your integration since 1 year and its working great so far. Thanks for the support 🙏

**Comment by wissamoh** [comment]
> Thanks @wissamoh! I didn't realize the Saudi region was actually not working anymore. We'll get this updated over the weekend.

You're welcome, and thanks for you too

**Comment by nshp** [comment]
Your fix is coming in v1.2.0, let me know if it keeps working.

**Comment by borski** [comment]
Closing issue as I believe this is fixed now. @wissamoh please let us know if it isn't working.
