### ISSUE TITLE
Integration fails to load after updating to 1.0.6

### ISSUE THREAD

**Issue by acronce** [borski/ha-lucidmotors#18]
I updated ha-lucidmotors to 1.0.6 and HA to 2024.5.5 today. After HA came back up, I noticed Watchman errors with Lucid entities.

Looking at the log, I see this:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 584, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lucidmotors/__init__.py", line 41, in async_setup_entry
    region = region_by_name(entry.data["region"])
                            ~~~~~~~~~~^^^^^^^^^^
KeyError: 'region'
```

Not sure this is relevant, but after I updated ha-lucidmotors I did not reboot HA at that point. I knew that the update of HA would also reboot, so I figured I'd save a reboot. Since then I've rebooted again and get the same error.

**Comment by nshp** [comment]
Bah, that's my bad. It was supposed to add that field automatically on upgrade and default to US. I guess I missed something. Will take a look later today. If you want to get it working in the meantime, you can delete your lucid "device" in the devices and integrations settings, then re-add it.

**Comment by acronce** [comment]
Thanks for the near instant reply! What I did for now was redownload 1.0.5.

I'd be happy to retest later when you've had a chance to look into this.

**Comment by nshp** [comment]
Fairly sure I've fixed this. 1.0.7 incoming.

**Comment by acronce** [comment]
HA was confused about which version was the latest (wanted me to update to v1.0.6). But after a couple of tries I've updated to 1.0.7 and the problem is gone. Watchman is happy, and the entities are available again.

Thanks for the fast fix!
