### ISSUE TITLE
Fails to load on HA Core 2024.6.0

### ISSUE THREAD

**Issue by marschind** [borski/ha-lucidmotors#19]
I updated the HA Core today to version 2024.6.0, and now get:

Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: 5:13:03 PM (3 occurrences)
Last logged: 5:13:34 PM
Unable to install package lucidmotors==1.1.2: ERROR: Cannot install lucidmotors==1.1.2 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by nshp** [comment]
Thanks, this should be fixed in v1.0.8. Let me know.

**Comment by marschind** [comment]
It works again!  Thanks.
