### ISSUE TITLE
Make frunk and trunk "cover" entities

### ISSUE THREAD

**Issue by nshp** [borski/ha-lucidmotors#2]
Not a huge deal, but I think the frunk and trunk should be Cover entities of type Door rather than Locks. This would mainly just make the buttons correct - you're not unlocking the trunk, you're opening it.

**Comment by borski** [comment]
@nshp We need to be a little careful here as in Pures that have a manual frunk, it really is more like a lock...

**Comment by borski** [comment]
Done in fc7411bb4051ba329793466bf207215d620985f8, except for handling manual frunks

**Comment by borski** [comment]
Finished in 0d00d6209c4fcfea1466fe6928d6c1981f9a7446
