### ISSUE TITLE
LucidMotors integration isn't compatible with new HA Core

### ISSUE THREAD

**Issue by marschind** [borski/ha-lucidmotors#23]
I just updated HA Core, and now I get this:

Logger: homeassistant.util.package
Source: util/package.py:152
First occurred: 10:47:07 PM (3 occurrences)
Last logged: 10:47:11 PM
Unable to install package lucidmotors==1.1.6: × No solution found when resolving dependencies: ╰─▶ Because lucidmotors==1.1.6 depends on grpcio==1.59.0 and grpcio==1.66.2, we can conclude that lucidmotors==1.1.6 cannot be used. And because you require lucidmotors==1.1.6, we can conclude that your requirements are unsatisfiable.

**Comment by Hajman** [comment]
Same issue for me.  I tried to uninstall and reinstall due this error, and that process fails with:

Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

**Comment by borski** [comment]
Thanks folks - sorry it took me a while to get to it. Fixed in v1.0.10. Please update in HACS and you should be good to go.

**Comment by marschind** [comment]
Any suggestions for how we can check for compatibility before HA updates?  I'd rather delay updates than break my Lucid integration.

**Comment by borski** [comment]
Sadly, no, not until we get it into HA mainline, which is a whole bunch of work I haven't had the desire to do yet.

Depending on how you're running HA, though, you should also be able to downgrade, potentially.

This isn't a common scenario though, to be fair; they updated some dependencies we relied on and we had some version mismatches as a result.
