### ISSUE TITLE
Add climate control entity

### ISSUE THREAD

**Issue by nshp** [borski/ha-lucidmotors#3]

**Comment by nshp** [comment]
Basic entity is there, but now I figure we should merge the Defrost setting into it. I don't think the car lets you turn on Defrost and general preconditioning at the same time.

**Comment by borski** [comment]
@nshp initial (somewhat broken) version of this here: https://github.com/borski/ha-lucidmotors/commit/42adcc571160293d7fb0c7963f50adfb27c13d37

**Comment by borski** [comment]
@nshp would you call this 'done'?

**Comment by nshp** [comment]
Done enough for today!
